### ISSUE TITLE
Add freetype2 to Stackage

### ISSUE THREAD

**Issue by Mokosha** [dagit/freetype2#4]
I'm not totally sure what the status of this package is, but is there any chance that we could add it to the [Stackage server](https://github.com/fpco/stackage/blob/master/build-constraints.yaml)? If not, what needs to be done to get it there? (I think we'd only need to specify a maintainer... I haven't had build problems on other platforms...?)

**Comment by dagit** [comment]
I don't use stackage so I wouldn't be a suitable maintainer, but I won't stop others from volunteering.

**Comment by Mokosha** [comment]
The current branches of freetype2 seem to be 4 years old. I noticed there's a pull request with 200+ changes with newer commits. I'd be happy to be the liaison with stackage for freetype2, but I'm not totally sure what the correct contributor workflow is for this repository (if issues come up).

**Comment by dagit** [comment]
Yeah, I have not kept the C code in this repo in sync with the official C freetype2 sources. That is really something that should be remedied. Freetype folks have released some security fixes over the years and we should pull those in for sure.

As for the PR, I totally forgot about that. I'm not sure I understand what it's doing. I think some people would rather have a binding that doesn't bundle the C sources and I think that PR makes that possible. When I originally made this binding, I erred on the side of simplicity for the person typing `cabal install freetype2`.

If you become maintainer of the stackage support then it would make sense to give you a commit bit. In terms of process, it's probably worth making issues and PRs and trying to communicate that way.

Hopefully that answers your questions.

**Comment by Mokosha** [comment]
I have a bit more time recently to look into this. I agree with bundling the C sources as it makes things less susceptible to the whims of whatever pkg-config nonsense can mess up builds. I'm not opposed to being the maintainer for stackage support, so ostensibly I can work on making that happen.

**Comment by Mokosha** [comment]
I think we should be good to go after we push a new build to hackage. We will likely need to change the minor version due to dependency changes in the cabal file.

**Comment by dagit** [comment]
How do you feel about making the hackage release? You've been the one working on this package the most recently and it might be good to get you permissions to update it.

**Comment by Mokosha** [comment]
SGTM. I'll still open bugs/let you know for significant changes. :)

**Comment by Mokosha** [comment]
OK, I bumped the version and generated a tarball. I just need Maintainer access to add it to hackage. My username is [Mokosha](https://hackage.haskell.org/user/Mokosha) on there, too.

**Comment by dagit** [comment]
I just added you on Hackage. Let me know if the upload works.
