### ISSUE TITLE
Improvements to freetype2

### ISSUE THREAD

**Issue by Mokosha** [dagit/freetype2#5]
I'd like to propose a few changes to this library, and I was hoping I could get your input (I can send pull requests for each of them):

1. Move freetype2 sources to a separate folder within the root of the directory to make it easier to distinguish Haskell source from freetype2 source.
2. Upgrade to the latest freetype2 version -- I believe that the latest is [2.7.1](https://sourceforge.net/projects/freetype/files/freetype2/2.7.1/)
3. Add this package to travis-ci so that we can test that it builds under different configurations.

What do you think?

**Comment by Mokosha** [comment]
Just for reference, the changes that I'm proposing would look like this:

https://github.com/Mokosha/freetype2/tree/AddTravisConfig

**Comment by dagit** [comment]
Looks good. Send me a PR and I'll merge it.

Thanks!
