### ISSUE TITLE
Dropping dependency on missing-foreign

### ISSUE THREAD

**Issue by mgmeier** [dagit/freetype2#6]
At a quick glance, all required Foreign functions are present in GHC's FFI since base >= 4.8, eliminating the need for an extra package & code duplication.

Depending on which GHC versions you still want to support, would you consider dropping missing-foreign from the dependencies?

This is a minor issue really, just asking out of curiosity.

**Comment by dagit** [comment]
Nice. When I made `missing-foreign` that wasn't the case. I'm not too worried about supporting older GHCs, but do you happen to know which versions ship 4.8 and newer?

**Comment by mgmeier** [comment]
GHC 7.10 shipped with base 4.8 (see: https://wiki.haskell.org/Base_package); the release was Apr. 2015. So there's still compatibility 2 years back.

You could check other hackage dependencies on ```missing-foreign```; also I saw that it is up on stackage, so there might be dependencies there. I'm not really familiar myself with what is best practice of deprecating and phasing out a Haskell package, so that's about the help I can give you...

**Comment by dagit** [comment]
This was addressed in Mokosha's pull request.
