### ISSUE TITLE
Handling API change

### ISSUE THREAD

**Issue by OlivierSohn** [dagit/freetype2#9]
Hello,

I was using the 0.1.* version, now I see that the 0.2.* version is a complete rewrite.

In stack resolver lts-16.10, the version is now 0.2.* which is not compatible with my code anymore.

Do I have to rewrite my code? I would prefer not to, obviously, because it would mean have 2 versions of the code. If I have to go this route, is there a migration guide to make it easier?

Or is it possible to also make the old 0.1.* version usable with ghc 8.8, through stack distributions ?

Thanks!

**Comment by Mokosha** [comment]
Hi Olivier,

If you use the resolver `lts-15.3` with `stack`, you should get version 0.1.2 of the library and GHC 8.8. If you need to use more up-to-date versions of GHC, you can likely use the [`extra-deps`](https://docs.haskellstack.org/en/stable/GUIDE/#curated-package-sets) field in your `stack.yaml`.

If that doesn't work, you will likely need to update your code, but if anything version 0.2 is more streamlined. There is no migration guide, and no plans to make one, but you can take a look at one of my projects where I did this upgrading myself:

https://github.com/Mokosha/Lambency/commit/2cd0d5a69ea4ea18af9913505dab47f337cf2221#diff-5baf8791753c1e331bfa0cab2d60698f
